services:
  # PHP Service
  develop:
    build:
      context: ./docker/develop
      args:
        - META_PATH
        - SRC_MOUNT_PATH
        - RUNTIME_PATH
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - ./:/srv/sites/web/:cached
    networks:
      - default
