services:
    # PHP Service
    develop:
        build:
            context: ./
            dockerfile: ./docker/develop/Dockerfile
        env_file:
            - .env
        ports:
            - "5000:5000"
        volumes:
            - ./:/srv/sites/web/:cached
        networks:
            - default
