services:
    # Development service
    develop:
        image: staticphp_develop
        container_name: staticphp_develop
        restart: "no"
        build:
            context: ./
            dockerfile: ./docker/app/Dockerfile
            target: development
        env_file:
            - .env
        ports:
            - "5500:5000"
        volumes:
            - ./:/srv/app:cached

    # Build service
    build:
        image: staticphp_build
        container_name: staticphp_build
        restart: "no"
        build:
            context: ./
            dockerfile: ./docker/app/Dockerfile
            target: build
        env_file:
            - .env
        volumes:
            - ./:/srv/app_mounted:cached
