services:
    # Mongo Database
    mongodb:
        image: mongo

    # Common image for development and build
    common:
        image: static_php_common
        build:
            context: ./docker/common
        env_file:
            - .env
        volumes:
            - ./:/srv/sites/web:cached

    # Development service
    develop:
        build:
            context: ./docker/develop
        env_file:
            - .env
        ports:
            - "5500:5000"
        volumes:
            - ./:/srv/sites/web:cached
        depends_on:
            - mongodb
            - common

    # Build service
    build:
        build:
            context: ./
            dockerfile: ./docker/build/Dockerfile
        env_file:
            - .env
        volumes:
            - ./:/srv/sites/web_mounted:cached
        depends_on:
            - common
